# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-01 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('productos', models.CharField(max_length=200)),
                ('cantidad', models.CharField(max_length=200)),
                ('abono', models.TextField(max_length=200)),
            ],
        ),
    ]
