# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
