# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-12 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20171006_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_mensual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_semanal',
        ),
    ]
