# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-11 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20171006_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
