# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.11 on 2017-09-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.9.11 on 2017-09-29 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> df24d45e659265e23318ffa9b13316302bbd27af


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> df24d45e659265e23318ffa9b13316302bbd27af
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.TextField(max_length=30)),
=======
                ('direccion', models.CharField(max_length=100)),
                ('cedula_identidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> df24d45e659265e23318ffa9b13316302bbd27af
            ],
        ),
    ]
